[build]
  base = "client"
  publish = "client/build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = ""

[[functions]]
  directory = "server/netlify-functions"
  node_bundler = "esbuild"

[functions]
  external_node_modules = ["express", "axios", "cors", "dotenv"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
